name: NoSpawn
main: me.xXLupoXx.NoSpawn.NoSpawn
author: xXLupoXx
version: 1.8
website: http://dev.bukkit.org/server-mods/nospawn/
softdepend: [Vault]
commands:
  nospawn:
    description: NoSpawn commands
    usage: 'Syntax: /<command> <allowspawn, denyspawn, despawn, setmoblimit, settotalmoblimit, usegbbl or settimer> <value>'
