name: NoSpawn
main: me.xXLupoXx.NoSpawn.NoSpawn
author: xXLupoXx
version: 1.6.1
website: http://forums.bukkit.org/threads/13926/
softdepend: [PermissionsEx]
commands:
  nospawn:
    description: NoSpawn commands
    usage: 'Syntax: /<command> <allowspawn, denyspawn, despawn, setmoblimit, settotalmoblimit or settimer> <value>'
